/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/1_name_social` | `/1_name_social`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/2_education` | `/2_education`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/3_ps` | `/3_ps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/4_pe` | `/4_pe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/5_projects` | `/5_projects`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/6_publications` | `/6_publications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/7_certifications` | `/7_certifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/8_skills` | `/8_skills`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/styling` | `/styling`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/1_name_social` | `/1_name_social`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/2_education` | `/2_education`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/3_ps` | `/3_ps`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/4_pe` | `/4_pe`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/5_projects` | `/5_projects`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/6_publications` | `/6_publications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/7_certifications` | `/7_certifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/8_skills` | `/8_skills`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/styling` | `/styling`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/1_name_social${`?${string}` | `#${string}` | ''}` | `/1_name_social${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/2_education${`?${string}` | `#${string}` | ''}` | `/2_education${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/3_ps${`?${string}` | `#${string}` | ''}` | `/3_ps${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/4_pe${`?${string}` | `#${string}` | ''}` | `/4_pe${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/5_projects${`?${string}` | `#${string}` | ''}` | `/5_projects${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/6_publications${`?${string}` | `#${string}` | ''}` | `/6_publications${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/7_certifications${`?${string}` | `#${string}` | ''}` | `/7_certifications${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/8_skills${`?${string}` | `#${string}` | ''}` | `/8_skills${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/styling${`?${string}` | `#${string}` | ''}` | `/styling${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/1_name_social` | `/1_name_social`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/2_education` | `/2_education`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/3_ps` | `/3_ps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/4_pe` | `/4_pe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/5_projects` | `/5_projects`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/6_publications` | `/6_publications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/7_certifications` | `/7_certifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/8_skills` | `/8_skills`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/styling` | `/styling`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
